# Generated by Django 6.1 on 2026-09-01 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0005_alter_subscription_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calories_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
